version: '3.8'

services:
  api_predictiva:
    container_name: pnp-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      # El túnel mágico: conecta tu carpeta local src/ con la del contenedor
      - ./src:/app/src
    command: uvicorn src.api.main:app --host 0.0.0.0 --port 8000 --reload
